### ISSUE TITLE
Getting InterruptedIOException: thread interrupted with persister

### ISSUE THREAD

**Issue by sourabhv** [NYTimes/Store#219]
I am getting these errors when using persister

    E: java.io.InterruptedIOException: thread interrupted
    E:     at okio.Timeout.throwIfReached(Timeout.java:146)
    E:     at okio.Okio$1.write(Okio.java:75)
    E:     at okio.AsyncTimeout$1.write(AsyncTimeout.java:179)
    E:     at okio.RealBufferedSink.flush(RealBufferedSink.java:216)
    E:     at okhttp3.internal.http1.Http1Codec.finishRequest(Http1Codec.java:166)
    E:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
    E:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    E:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    E:     at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:59)
    E:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    E:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
    E:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    E:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    E:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
    E:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    E:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    E:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    E:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    E:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
    E:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    E:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    E:     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:211)
    E:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    E:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    E:     at com.readystatesoftware.chuck.ChuckInterceptor.intercept(ChuckInterceptor.java:172)
    E:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    E:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    E:     at com.lifcare.launch.data.network.NetworkInterceptor.intercept(NetworkInterceptor.java:86)
    E:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    E:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    E:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
    E:     at okhttp3.RealCall.execute(RealCall.java:69)
    E:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
    E:     at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:40)
    E:     at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
    E:     at retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:33)
    E:     at retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:25)
    E:     at rx.Observable.unsafeSubscribe(Observable.java:10256)
    E:     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
    E:     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
    E:     at rx.Observable.unsafeSubscribe(Observable.java:10256)
    E:     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
    E:     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
    E:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    E:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    E:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    E:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    E:     at rx.Observable.unsafeSubscribe(Observable.java:10256)
    E:     at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
    E:     at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
    E:     at rx.Observable.unsafeSubscribe(Observable.java:10256)
    E:     at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
    E:     at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
    E:     at rx.Observable.unsafeSubscribe(Observable.java:10256)
    E:     at rx.internal.operators.CachedObservable$CacheState.connect(CachedObservable.java:183)
    E:     at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:248)
    E:     at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:230)
    E:     at rx.Observable.unsafeSubscribe(Observable.java:10256)
    E:     at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
    E:     at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
    E:     at rx.Observable.unsafeSubscribe(Observable.java:10256)
    E:     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
    E:     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
    E:     at rx.Observable.unsafeSubscribe(Observable.java:10256)
    E:     at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
    E:     at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
    E:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    E:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
    E:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    E:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
    E:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    E:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    E:     at java.lang.Thread.run(Thread.java:761)

And this

       java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
           at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
           at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
           at java.lang.Thread.run(Thread.java:761)
        Caused by: java.lang.NoSuchMethodError: No static method fromEmitter(Lrx/functions/Action1;Lrx/Emitter$BackpressureMode;)Lrx/Observable; in class Lrx/Observable; or its super classes (declaration of 'rx.Observable' appears in /data/app/com.lifcare.launch.debug-1/base.apk:classes55.dex)
           at com.nytimes.android.external.fs.FSReader.read(FSReader.java:34)
           at com.nytimes.android.external.fs.FileSystemPersister.read(FileSystemPersister.java:37)
           at com.nytimes.android.external.store.base.impl.RealInternalStore.readDisk(RealInternalStore.java:185)
           at com.nytimes.android.external.store.base.impl.RealInternalStore$12$1.call(RealInternalStore.java:274)
           at com.nytimes.android.external.store.base.impl.RealInternalStore$12$1.call(RealInternalStore.java:271)
           at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
           at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
           at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
           at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
           at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
           at rx.Observable.unsafeSubscribe(Observable.java:10256)
           at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
           at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
           at rx.Observable.unsafeSubscribe(Observable.java:10256)
           at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
           at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
           at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
           at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
           at retrofit2.adapter.rxjava.BodyOnSubscribe$BodySubscriber.onNext(BodyOnSubscribe.java:48)
           at retrofit2.adapter.rxjava.BodyOnSubscribe$BodySubscriber.onNext(BodyOnSubscribe.java:36)
           at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:115)
           at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:97)
           at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
           at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
           at retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:33)
           at retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:25)
           at rx.Observable.unsafeSubscribe(Observable.java:10256)
           at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
           at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
           at rx.Observable.unsafeSubscribe(Observable.java:10256)
           at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
           at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    E:     at rx.Observable.unsafeSubscribe(Observable.java:10256)
           at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
           at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
           at rx.Observable.unsafeSubscribe(Observable.java:10256)
           at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
           at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
           at rx.Observable.unsafeSubscribe(Observable.java:10256)
           at rx.internal.operators.CachedObservable$CacheState.connect(CachedObservable.java:183)
           at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:248)
           at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:230)
           at rx.Observable.unsafeSubscribe(Observable.java:10256)
           at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
           at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
           at rx.Observable.unsafeSubscribe(Observable.java:10256)
           at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
           at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
           at rx.Observable.unsafeSubscribe(Observable.java:10256)
           at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
           at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
           at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
            ... 6 more

Here is my store

        RealStoreBuilder<BufferedSource, WallObjectResponse, Long> store = StoreBuilder.parsedWithKey();
        store.parser(GsonParserFactory.createSourceParser(new Gson(), WallObjectResponse.class));
        try {
            store.persister(FileSystemPersister.create(FileSystemFactory.create(context.getFilesDir()), key -> "wall"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        store.fetcher(id -> restApi.getWallData(preferences.getCustomerId()).map(ResponseBody::source));
        this.store = store.open();

**Comment by digitalbuddha** [comment]
Seems like 2 different errors. First one is due to timeout from what I see. The second one we have a pr out to fix. #218 should fix the second one. 

When are you getting the interrupted exception? Is it every request? I noticed you have stetho and other interceptors could you try without them?

**Comment by digitalbuddha** [comment]
Closed for inactivity
