### ISSUE TITLE
java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets

### ISSUE THREAD

**Issue by png6** [NYTimes/Store#225]
I ran into a crash running the latest 2.1.0 release below,

> FATAL EXCEPTION: RxNewThreadScheduler-1
                                                                      java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                          at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
                                                                          at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                                                          at java.lang.Thread.run(Thread.java:856)
                                                                       Caused by: java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
                                                                          at com.nytimes.android.external.store.middleware.GsonBufferedSourceAdapter.toJson(GsonBufferedSourceAdapter.java:31)
                                                                          at com.nytimes.android.external.fs.ObjectToSourceTransformer.lambda$call$0(ObjectToSourceTransformer.java:25)
                                                                          at com.nytimes.android.external.fs.ObjectToSourceTransformer$$Lambda$1.call(Unknown Source)
                                                                          at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
                                                                          at retrofit2.adapter.rxjava.OperatorMapResponseToBodyOrError$1.onNext(OperatorMapResponseToBodyOrError.java:41)
                                                                          at retrofit2.adapter.rxjava.OperatorMapResponseToBodyOrError$1.onNext(OperatorMapResponseToBodyOrError.java:38)
                                                                          at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
                                                                          at rx.Subscriber.setProducer(Subscriber.java:211)
                                                                          at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
                                                                          at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
                                                                          at rx.Subscriber.setProducer(Subscriber.java:205)
                                                                          at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
                                                                          at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
                                                                          at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                                          at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                          at rx.Observable.unsafeSubscribe(Observable.java:10256)
                                                                          at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
                                                                          at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
                                                                          at rx.Observable.unsafeSubscribe(Observable.java:10256)
                                                                          at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
                                                                          at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
                                                                          at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                                          at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                          at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                                          at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                          at rx.Observable.unsafeSubscribe(Observable.java:10256)
                                                                          at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
                                                                          at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
                                                                          at rx.Observable.unsafeSubscribe(Observable.java:10256)
                                                                          at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
                                                                          at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
                                                                          at rx.Observable.unsafeSubscribe(Observable.java:10256)
                                                                          at rx.internal.operators.CachedObservable$CacheState.connect(CachedObservable.java:183)
                                                                          at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:248)
                                                                          at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:230)
                                                                          at rx.Observable.unsafeSubscribe(Observable.java:10256)
                                                                          at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
                                                                          at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
                                                                          at rx.Observable.unsafeSubscribe(Observable.java:10256)
                                                                      	at rx.internal.operators.OnS

I was running on a API 16 device and it looks like **StandardCharsets** was added in API 19 [https://developer.android.com/reference/java/nio/charset/StandardCharsets.html](url). It appears only GsonTransformerFactory.java uses it which makes sense since that's new in 2.1.0.

**Comment by digitalbuddha** [comment]
Thanks for finding! Will fix in am

**Comment by png6** [comment]
I was able to add workaround until a new release is available but luckily it's just a minor change to `Charset.forName("UTF-8")`.  I've confirmed it's working on fine on both API 16 and API 23 device.
