### ISSUE TITLE
new version 2.1.0 is broken

### ISSUE THREAD

**Issue by MuBoori** [NYTimes/Store#232]
Hi, I just found out about the library. I'm trying to run the demo code provided however, it does not work. 

I tried to follow the readme instruction but I cannot get anything running. Here is the code I tried

```
            Store<List<Post>, BarCode> postsStore  = StoreBuilder.<List<Post>>barcode()
                    .fetcher((barCode) -> ShbService.getRetrofitRx().create(UserService.class).getPostsRx())
                    .open();


            postsStore.get(new BarCode("test","1234"))
                    .subscribeOn(Schedulers.io())
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe(this::showPosts, throwable -> Log.w(TAG, throwable.getLocalizedMessage()));

```
I get the below message however, I tried to downgrade the library to 2.0.0 and the code works. 

~~~~
06-17 07:01:56.652 17481-17521/com.shb.sa.shwb E/AndroidRuntime: FATAL EXCEPTION: RxIoScheduler-2
                                                                 Process: com.shb.sa.shwb, PID: 17481
                                                                 java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                     at java.lang.Thread.run(Thread.java:761)
                                                                  Caused by: java.lang.NoSuchMethodError: No static method lambda$lazyCache$0(Lcom/nytimes/android/external/store/base/impl/RealInternalStore;Ljava/lang/Object;)Lrx/Observable; in class Lcom/nytimes/android/external/store/base/impl/RealInternalStore; or its super classes (declaration of 'com.nytimes.android.external.store.base.impl.RealInternalStore' appears in /data/app/com.shb.sa.shwb-1/split_lib_dependencies_apk.apk:classes2.dex)
                                                                     at com.nytimes.android.external.store.base.impl.RealInternalStore$$Lambda$1.call(Unknown Source)
                                                                     at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
                                                                     at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
                                                                     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                                     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                     at rx.Observable.unsafeSubscribe(Observable.java:10256)
                                                                     at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.drain(OnSubscribeConcatMap.java:286)
                                                                     at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.onNext(OnSubscribeConcatMap.java:144)
                                                                     at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.slowPath(OnSubscribeFromArray.java:100)
                                                                     at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:63)
                                                                     at rx.Subscriber.setProducer(Subscriber.java:211)
                                                                     at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
                                                                     at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
                                                                     at rx.Observable.unsafeSubscribe(Observable.java:10256)
                                                                     at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94)
                                                                     at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42)
                                                                     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                                     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                     at rx.Observable.unsafeSubscribe(Observable.java:10256)
                                                                     at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
                                                                     at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
                                                                     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                     at java.lang.Thread.run(Thread.java:761)

**Comment by digitalbuddha** [comment]
This is a bug in googles desugar tool. If you use Retrolambda for your app it will go away. Alternatively you can follow the tracker seems they identified the problem and are going to fix https://issuetracker.google.com/issues/62456849

**Comment by MuBoori** [comment]
@digitalbuddha Fantastic I installed retrolambda and now it works
https://github.com/evant/gradle-retrolambda

**Comment by digitalbuddha** [comment]
I'll update this issue once Google fixes problem on their side
