### ISSUE TITLE
Moshi Converter isn't working

### ISSUE THREAD

**Issue by FlorentDambreville** [NYTimes/Store#242]
Hello, 

I am not sure if this is an issue or if I am doing things wrong but I am unable to convert a BufferedSource (used for persistency) into my business class (Pollen) using 3.0.0-alpha Store version...
I am also using Kotlin, Retrofit & Moshi.

My StoreBuilder is the following : 
```Kotlin
fun providePersistedRedditStore(): Store<Pollen, BarCode> {
        return StoreBuilder.parsedWithKey<BarCode, BufferedSource, Pollen>()
                .fetcher({ barcode -> DataManager.fetchPollen(arrayOf(barcode.key, barcode.type)) })
                .persister(AppController.getAppController().persister)
                .parser(MoshiParserFactory.createSourceParser(Pollen::class.java))
                .open()
    }
```

My Retrofit builder is the following : 
```Kotlin
init {
        val retrofit = Retrofit.Builder()
                .baseUrl("https://socialpollencount.co.uk")
                .addConverterFactory(MoshiConverterFactory.create())
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                .build()

        gulliApi = retrofit.create(GulliApi::class.java)
    }
```

The error I get is the following (sorry for the huge block) : 
```
io.reactivex.exceptions.OnErrorNotImplementedException: java.lang.IllegalArgumentException: Unable to create converter for interface okio.BufferedSource
     for method GulliApi.getPollen
     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
     at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:45)
     at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
     at android.os.Handler.handleCallback(Handler.java:739)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:148)
     at android.app.ActivityThread.main(ActivityThread.java:5417)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 Caused by: com.nytimes.android.external.cache3.UncheckedExecutionException: java.lang.IllegalArgumentException: Unable to create converter for interface okio.BufferedSource
     for method GulliApi.getPollen
     at com.nytimes.android.external.cache3.LocalCache$Segment.get(LocalCache.java:2243)
     at com.nytimes.android.external.cache3.LocalCache.get(LocalCache.java:3983)
     at com.nytimes.android.external.cache3.LocalCache$LocalManualCache.get(LocalCache.java:4839)
     at com.nytimes.android.external.store3.base.impl.RealInternalStore.fetchAndPersist(RealInternalStore.java:176)
     at com.nytimes.android.external.store3.base.impl.RealInternalStore.lambda$fetch$6(RealInternalStore.java:160)
     at com.nytimes.android.external.store3.base.impl.RealInternalStore$$Lambda$7.call(Unknown Source)
     at io.reactivex.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:36)
     at io.reactivex.Single.subscribe(Single.java:2702)
     at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
     at io.reactivex.Maybe.subscribe(Maybe.java:3726)
     at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmpty$SwitchIfEmptyMaybeObserver.onComplete(MaybeSwitchIfEmpty.java:88)
     at io.reactivex.internal.operators.maybe.MaybeOnErrorNext$OnErrorNextMaybeObserver.onComplete(MaybeOnErrorNext.java:115)
     at io.reactivex.internal.operators.maybe.MaybeCache.onComplete(MaybeCache.java:113)
     at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onComplete(MaybePeek.java:167)
     at io.reactivex.internal.operators.maybe.MaybeMap$MapMaybeObserver.onComplete(MaybeMap.java:99)
     at io.reactivex.internal.operators.maybe.MaybeOnErrorNext$OnErrorNextMaybeObserver$NextMaybeObserver.onComplete(MaybeOnErrorNext.java:145)
     at io.reactivex.internal.disposables.EmptyDisposable.complete(EmptyDisposable.java:58)
     at io.reactivex.internal.operators.maybe.MaybeEmpty.subscribeActual(MaybeEmpty.java:29)
     at io.reactivex.Maybe.subscribe(Maybe.java:3726)
     at io.reactivex.internal.operators.maybe.MaybeOnErrorNext$OnErrorNextMaybeObserver.onError(MaybeOnErrorNext.java:110)
     at io.reactivex.internal.operators.maybe.MaybeCreate$Emitter.tryOnError(MaybeCreate.java:101)
     at io.reactivex.internal.operators.maybe.MaybeCreate$Emitter.onError(MaybeCreate.java:87)
     at com.nytimes.android.external.fs3.FSReader.lambda$read$0(FSReader.java:56)
     at com.nytimes.android.external.fs3.FSReader$$Lambda$1.subscribe(Unknown Source)
     at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
     at io.reactivex.Maybe.subscribe(Maybe.java:3726)
     at io.reactivex.internal.operators.maybe.MaybeOnErrorNext.subscribeActual(MaybeOnErrorNext.java:46)
     at io.reactivex.Maybe.subscribe(Maybe.java:3726)
     at io.reactivex.internal.operators.maybe.MaybeMap.subscribeActual(MaybeMap.java:40)
     at io.reactivex.Maybe.subscribe(Maybe.java:3726)
     at io.reactivex.internal.operators.maybe.MaybePeek.subscribeActual(MaybePeek.java:56)
     at io.reactivex.Maybe.subscribe(Maybe.java:3726)
     at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
     at io.reactivex.Maybe.subscribe(Maybe.java:3726)
     at io.reactivex.internal.operators.maybe.MaybeDefer.subscribeActual(MaybeDefer.java:48)
     at io.reactivex.Maybe.subscribe(Maybe.java:3726)
     at io.reactivex.internal.operators.maybe.MaybeOnErrorNext.subscribeActual(MaybeOnErrorNext.java:46)
     at io.reactivex.Maybe.subscribe(Maybe.java:3726)
     at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmpty.subscribeActual(MaybeSwitchIfEmpty.java:38)
     at io.reactivex.Maybe.subscribe(Maybe.java:3726)
     at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
     at io.reactivex.Single.subscribe(Single.java:2702)
     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
     at java.lang.Thread.run(Thread.java:818)
 Caused by: java.lang.IllegalArgumentException: Unable to create converter for interface okio.BufferedSource
     for method GulliApi.getPollen
     at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:751)
     at retrofit2.ServiceMethod$Builder.createResponseConverter(ServiceMethod.java:737)
     at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:168)
     at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:169)
     at retrofit2.Retrofit$1.invoke(Retrofit.java:146)
     at java.lang.reflect.Proxy.invoke(Proxy.java:393)
     at $Proxy1.getPollen(Unknown Source)
     at com.ldf.gulli.data.DataManager.fetchPollen(DataManager.kt:12)
     at com.ldf.gulli.data.StoreManager$providePersistedRedditStore$1.fetch(StoreManager.kt:19)
     at com.ldf.gulli.data.StoreManager$providePersistedRedditStore$1.fetch(StoreManager.kt:15)
     at com.nytimes.android.external.store3.base.impl.RealInternalStore.response(RealInternalStore.java:185)
     at com.nytimes.android.external.store3.base.impl.RealInternalStore.lambda$fetchAndPersist$7(RealInternalStore.java:176)
     at com.nytimes.android.external.store3.base.impl.RealInternalStore$$Lambda$8.call(Unknown Source)
     at com.nytimes.android.external.cache3.LocalCache$LocalManualCache$1.load(LocalCache.java:4842)
     at com.nytimes.android.external.cache3.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3554)
     at com.nytimes.android.external.cache3.LocalCache$Segment.loadSync(LocalCache.java:2359)
     at com.nytimes.android.external.cache3.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2322)
     at com.nytimes.android.external.cache3.LocalCache$Segment.get(LocalCache.java:2237)
 	... 50 more
 Caused by: java.lang.IllegalArgumentException: No JsonAdapter for interface okio.BufferedSource annotated []
     at com.squareup.moshi.Moshi.adapter(Moshi.java:115)
     at retrofit2.converter.moshi.MoshiConverterFactory.responseBodyConverter(MoshiConverterFactory.java:90)
     at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:328)
     at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:311)
     at retrofit2.ServiceMethod$Builder.createResponseConverter(ServiceMethod.java:735)
 	... 66 more
```

Can you help me ? 
Thank you for your time,

Florent

**Comment by FlorentDambreville** [comment]
Fixed my problem by telling retrofit that I am expecting a ResponseBody instead of a BufferedSource directly. 

Sorry for the inconvenience

**Comment by digitalbuddha** [comment]
you can also add a `BufferedSourceConverterFactory` to your retrofit instance

```

public final class BufferedSourceConverterFactory extends Converter.Factory {
  @Override
  public Converter<ResponseBody, ?> responseBodyConverter(Type type, Annotation[] annotations,
                                                          Retrofit retrofit) {
    if (!BufferedSource.class.equals(type)) {
      return null;
    }
    return new Converter<ResponseBody, BufferedSource>() {
      @Override public BufferedSource convert(ResponseBody value) throws IOException {
        return value.source();
      }
    };
  }
}
```

**Comment by FlorentDambreville** [comment]
Great thank you I'll do that !

**Comment by Shakezulla57** [comment]
@digitalbuddha  So then can you not use moshi if you're using BufferedSource? Aren't we supposed to use BufferedSource with FileSystemPersister?

**Comment by digitalbuddha** [comment]
I don't understand your question please restate.

**Comment by Shakezulla57** [comment]
Looking into it more I can add that `BufferedSourceConverterFactory` you posted and it works. Just to follow it through, Retrofit uses the converter on the `ResponseBody`, FileSystemPersister writes/reads the `BufferedSource` into the Moshi parser which then converts it into my class. Correct?

Sorry, long week and I'm just now diving into this library.

**Comment by digitalbuddha** [comment]
Yup that's the flow.

**Comment by Shakezulla57** [comment]
Awesome, thanks
